Create Design doc and base structure for the Library
ELEVATE-Project/frontend-authentication-module pull request #10
Opened 2024-02-21 17:03 UTC by Sumsum1231

Greetings **@kiranharidas187 @5Amogh** ,
I have made the suggested changes and now raising a PR kindly review it.

2024-02-22 16:55 UTC, Sumsum1231 commented
Improved some parts, @kiranharidas187 @5Amogh kindly review it.

2024-02-26 02:58 UTC, 5Amogh requested changes

2024-02-26 02:58 UTC, 5Amogh commented on package.json
Can you check on why this package.json is empty? and update accordingly

2024-02-26 03:07 UTC, 5Amogh commented
Please raise the PR against release-1.0.0 @Sumsum1231

2024-02-26 03:10 UTC, 5Amogh requested changes

2024-02-26 03:10 UTC, 5Amogh commented on package.json
are these two files package.json and package-lock.json are useful anywhere, can you re-check? as they're outside the frontend-auth-module, do they really matter?

2024-02-27 04:23 UTC, merged